clusters:
  - name: alpha
    machineType: n1-standard-1
    bootDiskSizeGb: 100
    zone: us-central1-a
    hubs:
    - name: a

fileservers:
  - name: 1
    machineType: n1-highmem-8
    dataDiskSizeGb: 1500
    zone: us-central1-a

# "Probability for Data Science" in berkeley.edu
project: striped-acrobat-186800
admins:
  - rylo@berkeley.edu
